### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by andrewskaggs**
Optimized background image file size and scrolling. Reduced opacity for better readability. Added recommended documentation files.

### CODE REVIEW

**Comment by andrewskaggs** [comment]
@tlengineer I think this complete the site, unless you have some specific wording you want me to add.

**Comment by tlengineer** [comment]
@andrewskaggs sweet dude! thanks a bunch!!

**Comment by tlengineer** [comment]
@andrewskaggs Actually I just thought of something. Instead of "Timothy S. Lee, P.E. (Gerogia), Proprietor", let's go back to what you had "Timothy S. Lee, P.E., Proprietor" but then a line of text under it in smaller font "Registered P.E. in the states of Georgia and Indiana.". That way, as I get more and more states as I'm about to get in the next weeks, I can just edit that one line.

**Comment by andrewskaggs** [comment]
Sure, I will update the PR with a line for that this evening.

**Comment by andrewskaggs** [comment]
@tlengineer 

Changes made. I set up a bulleted list you can add items to later without breaking any spacing, although I think it looks cleaner without actual bullet icons so I left them out. Instructions to add them back are in the CSS file if you choose.

You can click the "Merge pull request button" to apply the changes.

**Pull request merged**
